export const TOGGLE_COLOR = 'TOGGLE_COLOR';
export const EXAMPLE_REQUEST_START = 'EXAMPLE_REQUEST_START';
export const EXAMPLE_REQUEST_DATA = 'EXAMPLE_REQUEST_DATA';
export const TOGGLE_GIF = 'TOGGLE_GIF';
export const SECRET_CODE = 'SECRET_CODE';
